{
 "title": "Auth Tasks",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Tasks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(celery_tasks_executed_total{view!~\"prometheus-django-metrics|healthcheck|.*shop_product_import_1c_status\"}[$__rate_interval])) by(task, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Requests by Processing Time",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(celery_task_duration_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Init Tasks",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,5m,0),\n  task AS metric,\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskcompleted\nWHERE\n  $__timeFilter(time)\nGROUP BY 1, task\nORDER BY $__timeGroup(time,5m,0),\"id\""
    }
   ]
  },
  {
   "title": "Init Tasks",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,10s),\n  task AS metric,\n  avg(runtime) AS \"runtime\"\nFROM celeryanalytics_celerytaskcompleted\nWHERE\n  $__timeFilter(time)\nGROUP BY 1,2\nORDER BY $__timeGroup(time,10s)"
    }
   ]
  },
  {
   "title": "Fails",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,10m,0),\n  task AS metric,\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskfailed\nWHERE\n  $__timeFilter(time) \nGROUP BY 1,2\nORDER BY $__timeGroup(time,10m,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1m,0),\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskfailed\nWHERE\n  $__timeFilter(time) \nGROUP BY 1\nORDER BY $__timeGroup(time,1m,0)"
    }
   ]
  },
  {
   "title": "Pingbot Tasks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,5m,0),\n  \"Ping Task\" AS metric,\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskcompleted\nWHERE\n  $__timeFilter(time) and task in (\"pinger.tasks.corporation_notification_update\",  \"corporation_notification_update\")\nGROUP BY 1\nORDER BY $__timeGroup(time,5m,0),\"id\""
    }
   ]
  },
  {
   "title": "Database Sizes",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  TABLE_NAME AS `Table`,\r\n  TABLE_ROWS AS `Rows`,\r\n  ROUND((INDEX_LENGTH) / 1024 / 1024) AS `Index (MB)`,\r\n  ROUND((DATA_LENGTH) / 1024 / 1024) AS `Size (MB)`,\r\n  ROUND((INDEX_LENGTH+DATA_LENGTH) / 1024 / 1024) AS `Total (MB)`\r\nFROM\r\n  information_schema.TABLES\r\nWHERE\r\n  TABLE_SCHEMA = \"alliance_auth\"\r\nORDER BY\r\n  (DATA_LENGTH + INDEX_LENGTH)\r\nDESC;\r\n"
    }
   ]
  },
  {
   "title": "Failures in Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,5m,0),\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskfailed\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,5m,0)"
    }
   ]
  },
  {
   "title": "Max Tasks Per 10min Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,10m,0),\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskcompleted\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,10m,0)"
    }
   ]
  },
  {
   "title": "Tasks in Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,5m),\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskcompleted\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,5m)"
    }
   ]
  },
  {
   "title": "Max Tasks Failed Per 10min Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,5m,0),\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskfailed\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,5m,0)"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    table_name AS metric, \n    round(((data_length + index_length) / 1024 / 1024), 2) as \"value\"\nFROM information_schema.TABLES \nORDER BY (data_length + index_length) DESC;"
    }
   ]
  }
 ]
}