{
 "title": "ESI Requests Deep Dive",
 "description": "Django metrics dashboard using django-prometheus metrics exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(esi_request_total,endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ESI Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(esi_request_total{endpoint=\"$endpoint\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(esi_request_total{status_code=~\"2.+\", endpoint=\"$endpoint\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "3XX Responses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(esi_request_total{status_code=~\"3.+\", endpoint=\"$endpoint\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(esi_request_total{status_code=~\"4.+\", endpoint=\"$endpoint\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(esi_request_total{status_code=~\"5.+\", endpoint=\"$endpoint\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "ESI Response Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by(le) (rate(esi_requests_latency_by_endpoint_seconds_bucket{endpoint=\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ESI Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(esi_requests_latency_by_endpoint_seconds_bucket{endpoint=\"$endpoint\"}[1h])))",
     "legendFormat": "50 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(esi_requests_latency_by_endpoint_seconds_bucket{endpoint=\"$endpoint\"}[1h])))",
     "legendFormat": "95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(esi_requests_latency_by_endpoint_seconds_bucket{endpoint=\"$endpoint\"}[1h])))",
     "legendFormat": "99 quantile"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status_code) (irate(esi_request_total{endpoint=\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests in Time Period",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "esi_request_total{view!~\"prometheus-django-metrics|healthcheck|.*shop_product_import_1c_status\", endpoint=\"$endpoint\"}",
     "legendFormat": "{{endpoint}} ({{status_code}} - {{cache_status}})"
    }
   ]
  },
  {
   "title": "Remote Cache Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(cache_status) (irate(esi_request_total{endpoint=\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "504 Requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(endpoint, status_code) (increase(esi_request_total{view!~\"prometheus-django-metrics|healthcheck|.*shop_product_import_1c_status\", status_code=\"504\", endpoint=\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}